### ISSUE TITLE
What Ports Are Used For Discovery

### ISSUE THREAD

**Issue by CSimpiFoN** [forkd/netbox-scanner#13]
Hello,

Can you please confirm what ports are actually scanned in order to find the alive hosts on the network? This would be important what ports have to be allowed on the firewalls in order to let the application run properly.

Thanks and Regards

**Comment by forkd** [comment]
nmap performs the port scan and the parameter `-F` in configuration file forces to scan only the 100 most common ports.

You can change that behavior by editing nmap parameters in the configuration file.

Read https://nmap.org/book/man-port-specification.html for further info.
