### ISSUE TITLE
Getting Traceback Centos 7

### ISSUE THREAD

**Issue by jdtinsley88** [forkd/netbox-scanner#2]
Traceback (most recent call last):
  File "nbscanner", line 5, in <module>
    from configparser import ConfigParser
ImportError: No module named configparser

I have installed the following -

pip install configparser
Collecting configparser
  Downloading https://files.pythonhosted.org/packages/7c/69/c2ce7e91c89dc073eb1aa74c0621c3eefbffe8216b3f9af9d3885265c01c/configparser-3.5.0.tar.gz
Installing collected packages: configparser
  Running setup.py install for configparser ... done
Successfully installed configparser-3.5.0

But still running into that same issue.

**Comment by forkd** [comment]
I can't reproduce this error in my environment, but README shows the
best way to satisfy dependencies:

$ pip install -r requirements.txt

See README for more details. Let me know if this works.

Regards,
José Lopes

On Fri, Dec 21, 2018 at 4:15 PM jdtinsley88 <notifications@github.com> wrote:
>
> Traceback (most recent call last):
> File "nbscanner", line 5, in
> from configparser import ConfigParser
> ImportError: No module named configparser
>
> I have installed the following -
>
> pip install configparser
> Collecting configparser
> Downloading https://files.pythonhosted.org/packages/7c/69/c2ce7e91c89dc073eb1aa74c0621c3eefbffe8216b3f9af9d3885265c01c/configparser-3.5.0.tar.gz
> Installing collected packages: configparser
> Running setup.py install for configparser ... done
> Successfully installed configparser-3.5.0
>
> But still running into that same issue.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
José Lopes de Oliveira Jr.

**Comment by jdtinsley88** [comment]
Same thing.

 

I did go ahead and try this –

 

pip3 install netbox-scanner

 

However, I get the following but I cannot find a configuration file to modify – 

 

python nbscanner.py

  File "nbscanner.py", line 195

    parsing = self.parser([f'{h[0]}/32' for h in hosts])

 

Thanks,

Jordan

**Comment by forkd** [comment]
That is not the same problem.
f-strings are only present in Python 3.6+ and I noticed, you're using 3.5.
The first issue has a solution: https://github.com/forkd/netbox-scanner/issues/1

**Comment by jdtinsley88** [comment]
Okay, I installed python 3.7.0 from source.   Now I get this error even though I have nmap installed.

 

python3.7 nbscanner.py

Traceback (most recent call last):

  File "nbscanner.py", line 6, in <module>

    from nmap import PortScanner

ModuleNotFoundError: No module named 'nmap'

**Comment by forkd** [comment]
Man, CentOS is a bit different from other distros in Python3, please read the distro docs.

Maybe the best way to install Python3 in CentOS is shown below.

```
# yum -y install https://centos7.iuscommunity.org/ius-release.rpm
# yum -y update && yum -y upgrade
# yum install git python36u python36u-pip
#
# wget https://github.com/forkd/netbox-scanner/archive/master.zip
# unzip netbox-scanner-master.zip -d netbox-scanner
# cd netbox-scanner
# pip3.6 install -r requirements.txt
# python netbox-scanner/nbscanner
```

If your problem persists, I suggest you to use another Linux version or search in CentOS community, because that's not a problem with `netbox-scanner`, but with your setup.

**Comment by jdtinsley88** [comment]
I got it working now.

 

Also, a couple more questions –

 

1.	Is there any way to modify the description from nmap to include the MAC Address?
2.	How do you include tags to match up to different networks?  Such as “network1” for one subnet and “network2” for another subnet.

**Comment by forkd** [comment]
1. I really tried to do that, but Nmap can't find MAC addresses between networks*. It would be great to store that information.

2. There's no way to do that in the current version of netbox-scanner. It only adds a tag to allow admins control what is managed automatically by this script. In my case, I have seen no other use for tags. I control networks using the prefix field in NetBox.

Good to know it it working right now.

* https://stackoverflow.com/questions/13212187/is-it-possible-to-get-the-mac-address-for-machine-using-nmap
