### ISSUE TITLE
Traceback on Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by gazza-d** [forkd/netbox-scanner#3]
Hi

I'm getting the following traceback error on Ubuntu 18.04.2
I installed netbox-scanner by pip3 as per the instructions, and have checked the requirements have been installed. I am running Python 2.7.15rc1

any ideas?

`Traceback (most recent call last):
  File "nbscanner", line 10, in <module>
    from urllib3 import disable_warnings
ImportError: No module named urllib3`

**Comment by forkd** [comment]
Hi,

Python 3.6+ is pre requisite.

Looks like you installed all modules in Python 3 and executed this script in Python 2. When running netbox-scanner force using Python 3 with `python3` command. Assure you have v3.6+.

**Comment by gazza-d** [comment]
Doh!!

Thanks for the swift response. It's now working.

**Comment by forkd** [comment]
No prob. Closing issue.
